# Generated by Django 3.2.15 on 2022-09-17 23:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('vulnerabilityid', models.CharField(default=uuid.uuid4, max_length=30, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('analysisid', models.CharField(max_length=50)),
                ('vulnerabilitytitle', models.CharField(max_length=100)),
                ('vulnerabilitydescription', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=500)),
                ('lineofcode', models.PositiveIntegerField()),
                ('commitid', models.CharField(max_length=100)),
                ('falsepositive', models.BooleanField()),
            ],
        ),
    ]
