# Generated by Django 3.2.15 on 2022-09-18 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_vulnerability_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysisid', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=50)),
                ('startedat', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
