# Generated by Django 3.2.15 on 2022-09-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='name',
            field=models.CharField(default='Test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='repositoryurl',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='state',
            field=models.CharField(default='New', max_length=100),
            preserve_default=False,
        ),
    ]
