# Generated by Django 4.1.4 on 2023-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_remove_vulnerability_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='username',
            field=models.TextField(default='test_user1'),
            preserve_default=False,
        ),
    ]
