# Generated by Django 4.1.4 on 2023-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0009_analysis_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
