# Generated by Django 4.1.4 on 2023-01-06 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scans', '0012_alter_analysis_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='userid',
            field=models.ForeignKey(db_column='username', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
