# Generated by Django 4.1.4 on 2023-01-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0018_alter_analysis_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='userid',
            field=models.CharField(max_length=50),
        ),
    ]
