# Generated by Django 4.1.4 on 2023-01-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0026_alter_analysis_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
